development:
  adapter: mysql2
  encoding: utf8
  database: metrogaslecturas_db
  username: root
  password: P@ssw0rd666
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: metrogaslecturas_db
  username: root
  password: P@ssw0rd666
  host: 127.0.0.1
